### ISSUE TITLE
Implementing a document read counter by user using painless

### ISSUE THREAD

**Issue by Analect** [PacktPublishing/Mastering-Elasticsearch-5.x-Third-Edition#1]
@packtprasadr 
I came across your repo while searching for `painless` examples.  As you know, the documentation and examples on elastic's own site are few and far between.

As per this forum [post](https://discuss.elastic.co/t/using-painless-script-to-add-append-to-a-nested-field/57290) some months ago, I had been trying to solve this with painless, but had no joy in solving.  I wonder if you would have some sense for how this could be accomplished with painless.  It might make a good example for one of your chapters!

I'll regenerate the initial description from the forum thread here:

I have a document with a nested 'views' field, containing a 'user' and a 'count' value.

```
"views": 
[{"count": 2,
"user": "tt99"},
{"count":1,
"user: "tt88"}]
```

I'm trying to figure out a 'painless' script that, depending on the supplied parameters, either:
(a) adds the field "views", along with a user and default count of 1, when the field does not pre-exist;
(b) where the field does pre-exist, it appends the new user and a default count of 1 to the views array; or
(c) where both the field and user pre-exist, it just increments the counter by one, but doesn't duplicate the user.

I have tried this (which I know doesn't handle the field not pre-existing):

```
POST index/type/12345/_update
{
"script": {
"lang": "painless",
"inline": "if (ctx.source.views.user === params.view.user) {ctx.source.views.count += params.view.count} else {ctx._source.views += params.view}",
"params": {
"view": {"user":"tt99", "count":1}
}
}
}
```
However, it doesn't like how I am reference user: "Illegal list shortcut value [user]."

In the case above, I would expect, as my result, the count to increment to 3. If my params were {"user":"tt77", "count":1}, I would expect a new user "tt77" with count of 1 to get appended to the views array.

Should I be somehow looping through the json docs within the views array? I have seen a groovy example referencing a 'containskey' function .. but I tried that in 'painless' without any joy.  You can see the thread for a few other approaches I took, but none appear to work.  I would be curious if have an alternative approach that might work.

Thanks.

**Comment by Analect** [comment]
@bharvidixit ... just wanted to bump this again, since I don't think @packtprasadr is necessarily an actively-used username.  Any thoughts on the above and how to implement it with painless?  Thanks.

**Comment by AurobindoKar** [comment]
Hi,

I am closing the issue.
In case the issue still persists, feel free to reopen it.

Thanks
